all:
	echo 'Usage: see https://github.com/rounds/10M-Docker-Images/blob/master/base/README.md'

.build:
	if [ -e Dockerfile ]; then docker build --tag "$(IMAGE_NAME)" .; fi;
	if [ -e cached/Dockerfile ]; then docker build --tag "$(IMAGE_NAME)" cached; fi;

build: .build

build-parent:
	$(MAKE) -C .. build-cascade

clean:
	if [ -e Dockerfile ] || [ -e cached/Dockerfile ]; then docker rmi -f "$(IMAGE_NAME)"; fi;

clean-parent:
	$(MAKE) -C .. clean-cascade

push-only:
	if [ -e Dockerfile ] || [ -e cached/Dockerfile ]; then docker push "$(IMAGE_NAME)"; fi;

push: build push-only

push-parent:
	$(MAKE) -C .. push-cascade

run:
	if [ -e Dockerfile ] || [ -e cached/Dockerfile ]; then docker run --rm -it "$(IMAGE_NAME)" bash; fi;

dep:
	#* Currently assuming you have docker installed, the deamon running and permissions to access it on current user
	#* Currently assuming you have python-pip, if not: \
apt-install python-pip \
yum install python-pip \
TODO: use peru inside docker?"
	#* Installing peru pip package
	pip3 install peru

update-helper-start:
	peru reup -f
	peru sync

update-helper-end:
	sed -i -e "1s/^/\
# *** DO NOT EDIT THIS FILE MANUALLY ***\n\
# *** Will be overwritten by 'make update' ***\n/" cached/Dockerfile # Outside file warning
